rollOutCiliumPods: true

priorityClassName: "system-node-critical"

annotateK8sNode: true

containerRuntime:
  integration: containerd
  socketPath: /var/run/containerd/containerd.sock

encryption:
  enabled: true
  type: wireguard

operator:
  replicas: 1

l7Proxy: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    rollOutPods: true

ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDR: "10.111.0.0/12"

policyEnforcementMode: "none"

kubeProxyReplacement: "strict"
k8sServiceHost: "admin.alleaffengaffen.ch"
k8sServicePort: "6443"
